# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gaomingye/ttcp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gaomingye/ttcp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gaomingye/ttcp/CMakeFiles /home/gaomingye/ttcp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gaomingye/ttcp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ttcp

# Build rule for target.
ttcp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ttcp
.PHONY : ttcp

# fast build rule for target.
ttcp/fast:
	$(MAKE) -f CMakeFiles/ttcp.dir/build.make CMakeFiles/ttcp.dir/build
.PHONY : ttcp/fast

main.o: main.cc.o

.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) -f CMakeFiles/ttcp.dir/build.make CMakeFiles/ttcp.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i

.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) -f CMakeFiles/ttcp.dir/build.make CMakeFiles/ttcp.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s

.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) -f CMakeFiles/ttcp.dir/build.make CMakeFiles/ttcp.dir/main.cc.s
.PHONY : main.cc.s

parseCommandLine.o: parseCommandLine.cc.o

.PHONY : parseCommandLine.o

# target to build an object file
parseCommandLine.cc.o:
	$(MAKE) -f CMakeFiles/ttcp.dir/build.make CMakeFiles/ttcp.dir/parseCommandLine.cc.o
.PHONY : parseCommandLine.cc.o

parseCommandLine.i: parseCommandLine.cc.i

.PHONY : parseCommandLine.i

# target to preprocess a source file
parseCommandLine.cc.i:
	$(MAKE) -f CMakeFiles/ttcp.dir/build.make CMakeFiles/ttcp.dir/parseCommandLine.cc.i
.PHONY : parseCommandLine.cc.i

parseCommandLine.s: parseCommandLine.cc.s

.PHONY : parseCommandLine.s

# target to generate assembly for a file
parseCommandLine.cc.s:
	$(MAKE) -f CMakeFiles/ttcp.dir/build.make CMakeFiles/ttcp.dir/parseCommandLine.cc.s
.PHONY : parseCommandLine.cc.s

socketOp.o: socketOp.cc.o

.PHONY : socketOp.o

# target to build an object file
socketOp.cc.o:
	$(MAKE) -f CMakeFiles/ttcp.dir/build.make CMakeFiles/ttcp.dir/socketOp.cc.o
.PHONY : socketOp.cc.o

socketOp.i: socketOp.cc.i

.PHONY : socketOp.i

# target to preprocess a source file
socketOp.cc.i:
	$(MAKE) -f CMakeFiles/ttcp.dir/build.make CMakeFiles/ttcp.dir/socketOp.cc.i
.PHONY : socketOp.cc.i

socketOp.s: socketOp.cc.s

.PHONY : socketOp.s

# target to generate assembly for a file
socketOp.cc.s:
	$(MAKE) -f CMakeFiles/ttcp.dir/build.make CMakeFiles/ttcp.dir/socketOp.cc.s
.PHONY : socketOp.cc.s

ttcp.o: ttcp.cc.o

.PHONY : ttcp.o

# target to build an object file
ttcp.cc.o:
	$(MAKE) -f CMakeFiles/ttcp.dir/build.make CMakeFiles/ttcp.dir/ttcp.cc.o
.PHONY : ttcp.cc.o

ttcp.i: ttcp.cc.i

.PHONY : ttcp.i

# target to preprocess a source file
ttcp.cc.i:
	$(MAKE) -f CMakeFiles/ttcp.dir/build.make CMakeFiles/ttcp.dir/ttcp.cc.i
.PHONY : ttcp.cc.i

ttcp.s: ttcp.cc.s

.PHONY : ttcp.s

# target to generate assembly for a file
ttcp.cc.s:
	$(MAKE) -f CMakeFiles/ttcp.dir/build.make CMakeFiles/ttcp.dir/ttcp.cc.s
.PHONY : ttcp.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ttcp"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parseCommandLine.o"
	@echo "... parseCommandLine.i"
	@echo "... parseCommandLine.s"
	@echo "... socketOp.o"
	@echo "... socketOp.i"
	@echo "... socketOp.s"
	@echo "... ttcp.o"
	@echo "... ttcp.i"
	@echo "... ttcp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

